In [2]:
 import numpy as np
a = np.arange(24)

In [3]:
a.size

24

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
a=np.array([[1,2,3,4],[4,5,6,7]])
a.shape=(8,1)
print(a.ndim)
print(a)

2
[[1]
 [2]
 [3]
 [4]
 [4]
 [5]
 [6]
 [7]]


In [15]:
a=np.arange(24)
print(a.ndim)
b=a.reshape(2,3,4,)
print(b.ndim)


1
3


In [17]:
a.dtype

dtype('int32')

In [18]:
b=np.linspace(5,7,11)
print(b)
print(b.dtype)

[5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7. ]
float64


In [23]:
a= np.array([5,10])
np.sum(a)

15

In [28]:
b=[2,3]
print(np.sum(a))
print(np.subtract(a,b))

15
[3 7]


In [29]:
a= np.arange(24,dtype = float)
print(a.size)
print(a.dtype)
b= a.reshape(3,4,2)
b

24
float64


array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

In [43]:
a=[1,2,4]
b=[2,4,4]
c=[1,2,4]
np.equal(a,b)
print(np.array_equal(a,b))

False


In [49]:
a=(1,2,3)
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
print(np.corrcoef(a))

6
1
3
2.0
0.816496580927726
2.0
1.0


In [50]:
a=10
name="victor"
salaty=200.23
print(a)
print(name)
print(salaty)

10
victor
200.23


In [51]:
1+2

3

In [52]:
a=10
b=10
c=0
a=b=c=10
x=20
y=30
z=40
x,y,z=20,30,40
print(y,a)

30 10


In [53]:
A=30
a=20
print(A)
print(a)

30
20


In [56]:
a_b=10
print(a_b)

10


In [57]:
_nik=10
print(_nik)

10


In [65]:
multiline="""nik
nik
nik2......
"""
print(multiline)

nik
nik
nik2......



In [67]:
text1 ="hello-world"
print(text1)

hello-world


In [70]:
a=10
val= None
print(a)
print({val})

10
{None}


In [72]:
8/2

4.0

In [73]:
a=10
a*=10
print(a)

100


In [74]:
nik=50
nik+=50
print(nik)

100


In [76]:
nik-=200
print(nik)

-200


In [81]:
a=10>15 or 25>20 and 10>8
print(a)

True


In [82]:
    #1 0 1     in bainary form
7|5 #1 2 4 8 12 16 18
     1 1 1

7

In [83]:
7&5

5

In [85]:
10>>2

2

In [86]:
10<<2 #1010000:40


40

In [87]:
10<<3

80

In [99]:
x=10
x is 10

True

In [100]:
x is not 10

False

In [102]:
pets=["dog","cat","wolf"]
"lion" in pets

False

In [103]:
"wolf" in pets

True

In [104]:
"me" in "appoinment"


True

In [105]:
a=10
name="rak"
pay=120.22
print(type(a))
print(type(name))
print(type(pay))

<class 'int'>
<class 'str'>
<class 'float'>


In [109]:
varable="hello-world"
varable2="python game"
print(varable[0:5])
print(varable2[0:7])

hello
python 


In [114]:
string="hello friend"
string2="internet"
print (string[0])
print(string2[-1])

h
t


In [117]:
string="attachment"
string.find("ment")

6

In [118]:
string="replacment"
string.replace("ment","")

'replac'

In [130]:
string2= 'world'
print(string2)

world
